function [ horizDeriv_Sigma1_imageData,vertDeriv_Sigma1_imageData,...
    horizDeriv_Sigma2_imageData,vertDeriv_Sigma2_imageData,...
    horizDeriv_Sigma4_imageData,vertDeriv_Sigma4_imageData,...
    gaussDiff_4_2_imageData,gaussDiff_2_1_imageData] = get8FilterImages( imageData,imname )
%GET8FILTERIMAGES Summary of this function goes here
%   Detailed explanation goes here

[horizDeriv_Sigma1_imageData,vertDeriv_Sigma1_imageData] =...
    computeDerivImages(imageData,1,imname);
[horizDeriv_Sigma2_imageData,vertDeriv_Sigma2_imageData] =...
    computeDerivImages(imageData,2,imname);
[horizDeriv_Sigma4_imageData,vertDeriv_Sigma4_imageData] =...
    computeDerivImages(imageData,4,imname);
gaussDiff_4_2_imageData = computeGaussDiff(imageData,1,2,imname);
gaussDiff_2_1_imageData = computeGaussDiff(imageData,2,4,imname);
end

